class Lexicon:
    bomb_collected = "La bomba ha sido recolectada."
    boxes_collected = "Número de cajas recolectadas"
    boxes_remaining = "Número de cajas restantes"
    boxes_to_collect = "Número de cajas para recolectar"
    instructions = "Instrucciones"
    no = "No"
    results = 'Resultados'
    round_history = "Historial de rondas"
    round_number = "Ronda N°"
    round_payoff = "Pago de la ronda"
    solve = "Resolver"
    start = "Empezar"
    stop = "Detener"
    yes = "Sí"
    your_decision = "Tu decisión"
