from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)

author = 'Your name here'

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'exp1'
    players_per_group = None
    num_rounds = 1
    instructions_template = 'increasing_t1/Instructions.html'
    determined_series = [[143,
                          174,
                          117,
                          200,
                          145,
                          158,
                          148,
                          183,
                          181,
                          190,
                          217,
                          154,
                          175,
                          174,
                          193,
                          189,
                          213,
                          161,
                          224,
                          202,
                          168,
                          195,
                          219,
                          230,
                          227,
                          248,
                          218,
                          241,
                          270,
                          261,
                          254,
                          280,
                          316,
                          333,
                          309,
                          341,
                          360,
                          377,
                          360,
                          379,
                          403,
                          397,
                          401,
                          451,
                          425,
                          445,
                          469,
                          430,
                          458,
                          514,
                          551,
                          544,
                          553,
                          552,
                          548,
                          560,
                          561,
                          584,
                          574,
                          610,
                          639,
                          634,
                          637,
                          639,
                          680,
                          630,
                          683,
                          666,
                          712,
                          700,
                          694,
                          683,
                          747,
                          703,
                          703,
                          700,
                          696,
                          750,
                          679,
                          708,
                          747,
                          710,
                          697,
                          735,
                          688,
                          750,
                          736,
                          750,
                          741,
                          774,
                          740,
                          721,
                          721,
                          750,
                          741,
                          752,
                          719,
                          733,
                          720,
                          701,
                          714,
                          711,
                          756,
                          722,
                          737,
                          726,
                          717,
                          711,
                          702,
                          672,
                          717,
                          725,
                          689,
                          631,
                          682,
                          683,
                          635,
                          647,
                          650,
                          675,
                          636,
                          596,
                          578,
                          619,
                          600,
                          572,
                          546,
                          538,
                          542,
                          534,
                          504,
                          498,
                          492,
                          514,
                          478,
                          458,
                          422,
                          389,
                          396,
                          374,
                          371,
                          363,
                          378,
                          356,
                          335,
                          313,
                          294,
                          336,
                          286,
                          262,
                          294,
                          262,
                          275,
                          235,
                          230,
                          242,
                          213,
                          233,
                          218,
                          223,
                          198,
                          227,
                          196,
                          215,
                          225,
                          214,
                          153,
                          193,
                          166,
                          186,
                          171,
                          148,
                          178,
                          203,
                          151,
                          143,
                          161,
                          170,
                          149,
                          169,
                          151,
                          163,
                          177,
                          151,
                          146,
                          141,
                          138,
                          132,
                          140,
                          179,
                          145,
                          163,
                          114,
                          157,
                          177,
                          180,
                          147,
                          186,
                          150,
                          177,
                          171,
                          181,
                          176,
                          167,
                          199,
                          170,
                          179,
                          192,
                          141,
                          206,
                          188,
                          191,
                          159,
                          220,
                          178,
                          227,
                          227,
                          239,
                          208,
                          240,
                          238],
                         [143,
                          159,
                          205,
                          173,
                          151,
                          176,
                          199,
                          187,
                          189,
                          156,
                          177,
                          171,
                          155,
                          185,
                          156,
                          167,
                          167,
                          191,
                          178,
                          179,
                          168,
                          196,
                          218,
                          243,
                          246,
                          226,
                          221,
                          207,
                          228,
                          274,
                          299,
                          255,
                          287,
                          303,
                          302,
                          317,
                          364,
                          366,
                          374,
                          393,
                          364,
                          410,
                          414,
                          407,
                          424,
                          428,
                          445,
                          502,
                          447,
                          452,
                          514,
                          527,
                          502,
                          520,
                          562,
                          580,
                          576,
                          600,
                          594,
                          642,
                          626,
                          612,
                          642,
                          651,
                          683,
                          675,
                          681,
                          690,
                          703,
                          655,
                          679,
                          679,
                          691,
                          720,
                          714,
                          735,
                          689,
                          751,
                          725,
                          722,
                          753,
                          701,
                          714,
                          710,
                          750,
                          757,
                          745,
                          746,
                          741,
                          743,
                          728,
                          763,
                          745,
                          734,
                          784,
                          707,
                          733,
                          739,
                          746,
                          726,
                          734,
                          715,
                          680,
                          720,
                          702,
                          684,
                          719,
                          742,
                          715,
                          679,
                          704,
                          683,
                          657,
                          675,
                          663,
                          657,
                          631,
                          679,
                          649,
                          646,
                          602,
                          667,
                          624,
                          563,
                          590,
                          599,
                          568,
                          561,
                          552,
                          548,
                          508,
                          472,
                          504,
                          508,
                          466,
                          474,
                          464,
                          403,
                          437,
                          381,
                          357,
                          358,
                          368,
                          380,
                          334,
                          312,
                          324,
                          291,
                          271,
                          285,
                          240,
                          260,
                          253,
                          269,
                          207,
                          213,
                          239,
                          236,
                          226,
                          220,
                          208,
                          216,
                          208,
                          187,
                          194,
                          188,
                          196,
                          146,
                          166,
                          195,
                          200,
                          140,
                          178,
                          176,
                          148,
                          176,
                          192,
                          187,
                          160,
                          201,
                          130,
                          168,
                          178,
                          126,
                          162,
                          132,
                          178,
                          170,
                          157,
                          155,
                          102,
                          175,
                          172,
                          153,
                          182,
                          132,
                          152,
                          144,
                          163,
                          124,
                          181,
                          187,
                          185,
                          160,
                          162,
                          194,
                          189,
                          172,
                          181,
                          214,
                          202,
                          207,
                          190,
                          185,
                          199,
                          208,
                          210,
                          208,
                          222,
                          195,
                          255],
                         [143,
                          196,
                          187,
                          127,
                          167,
                          141,
                          182,
                          153,
                          204,
                          210,
                          160,
                          184,
                          170,
                          164,
                          196,
                          178,
                          198,
                          222,
                          229,
                          169,
                          224,
                          228,
                          239,
                          227,
                          221,
                          272,
                          213,
                          279,
                          289,
                          265,
                          273,
                          316,
                          276,
                          337,
                          326,
                          326,
                          322,
                          361,
                          383,
                          382,
                          409,
                          388,
                          414,
                          408,
                          445,
                          443,
                          465,
                          440,
                          513,
                          484,
                          480,
                          533,
                          553,
                          560,
                          551,
                          580,
                          579,
                          560,
                          630,
                          615,
                          620,
                          644,
                          695,
                          647,
                          651,
                          677,
                          690,
                          667,
                          700,
                          695,
                          714,
                          719,
                          715,
                          675,
                          669,
                          709,
                          712,
                          713,
                          719,
                          754,
                          677,
                          721,
                          703,
                          702,
                          735,
                          778,
                          736,
                          703,
                          768,
                          764,
                          705,
                          766,
                          718,
                          738,
                          737,
                          735,
                          724,
                          703,
                          759,
                          714,
                          688,
                          702,
                          738,
                          686,
                          701,
                          712,
                          726,
                          683,
                          743,
                          692,
                          687,
                          682,
                          707,
                          690,
                          659,
                          670,
                          673,
                          695,
                          645,
                          604,
                          606,
                          612,
                          653,
                          557,
                          568,
                          585,
                          544,
                          586,
                          514,
                          522,
                          502,
                          466,
                          531,
                          460,
                          465,
                          442,
                          432,
                          435,
                          402,
                          397,
                          410,
                          388,
                          368,
                          350,
                          350,
                          322,
                          292,
                          306,
                          298,
                          283,
                          280,
                          277,
                          272,
                          232,
                          225,
                          221,
                          206,
                          227,
                          237,
                          261,
                          229,
                          184,
                          184,
                          212,
                          219,
                          192,
                          183,
                          158,
                          175,
                          185,
                          175,
                          167,
                          150,
                          170,
                          172,
                          162,
                          128,
                          201,
                          162,
                          169,
                          167,
                          180,
                          145,
                          169,
                          158,
                          111,
                          157,
                          128,
                          185,
                          171,
                          166,
                          149,
                          138,
                          163,
                          166,
                          142,
                          150,
                          147,
                          152,
                          177,
                          146,
                          168,
                          202,
                          168,
                          181,
                          196,
                          167,
                          209,
                          206,
                          196,
                          170,
                          189,
                          175,
                          216,
                          203,
                          202,
                          183,
                          199,
                          228,
                          219,
                          230]]


class Subsession(BaseSubsession):
    def creating_session(self):
        players = self.get_players()
        for p in players:
            p.new_round_number = p.round_number + 11


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    CQ1 = models.StringField(
        choices=['Below 100',
                 'Between 100 and 300',
                 'Between 300 and 500',
                 'Above 500'],
        widget=widgets.RadioSelect
    )

    def CQ1_error_message(self, value):
        if value != 'Between 100 and 300':
            return 'In the graph, the number of daily infection cases is between 100 and 300.'

    CQ2 = models.StringField(
        choices=['forecast daily infection cases for a virus',
                 'forecast monthly infection cases for a virus',
                 'forecast annual infection cases for a virus', ],
        widget=widgets.RadioSelect
    )

    def CQ2_error_message(self, value):
        if value != 'forecast daily infection cases for a virus':
            return 'In this study, your main task is to forecast daily infection cases for a virus.'

    CQ3 = models.StringField(
        choices=['10 days from now',
                 '20 days from now',
                 '30 days from now',
                 '180 days and 365 days from now'],
        widget=widgets.RadioSelect
    )

    def CQ3_error_message(self, value):
        if value != '10 days from now':
            return 'In the graph, the forecast horizon which the red vertical line indicates is \'10 days from now.\''

    CQ4 = models.StringField(
        choices=['The study setting is hypothetical.',
                 'The new virus in the experiment has relation to the current COVID outbreak.',
                 'Currently no effective vaccine exists for the virus.',
                 'It is expected to take 6 months to develop the new effective vaccine from now (day 220).'],
        widget=widgets.RadioSelect
    )

    def CQ4_error_message(self, value):
        if value != 'The new virus in the experiment has relation to the current COVID outbreak.':
            return 'The new virus in this study has NO relation to the current COVID outbreak.'

    forecast_10 = models.IntegerField()

    def forecast_10_error_message(self, value):
        if value < 100 or value > 1000:
            return 'Please make your forecast within the range of the graph(100-1000). Please revise your forecast.'

    forecast_20 = models.IntegerField()

    def forecast_20_error_message(self, value):
        if value < 100 or value > 1000:
            return 'Please make your forecast within the range of the graph(100-1000). Please revise your forecast.'

    forecast_30 = models.IntegerField()

    def forecast_30_error_message(self, value):
        if value < 100 or value > 1000:
            return 'Please make your forecast within the range of the graph(100-1000). Please revise your forecast.'

    forecast_6m = models.IntegerField()

    def forecast_6m_error_message(self, value):
        if value < 0:
            return 'Infection cases cannot be a negative number. Please revise your forecast.'

    forecast_1y = models.IntegerField()

    def forecast_1y_error_message(self, value):
        if value < 0:
            return 'Infection cases cannot be a negative number. Please revise your forecast.'

    actual_10 = models.IntegerField()
    actual_20 = models.IntegerField()
    actual_30 = models.IntegerField()
    new_round_number = models.IntegerField()

    time_spent1 = models.FloatField()
    time_spent2 = models.FloatField()
    time_spent3 = models.FloatField()
    time_spent4 = models.FloatField()
